// Code generated by ent, DO NOT EDIT.

package oauthcode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/hcchien/nl/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// CodeHash applies equality check predicate on the "code_hash" field. It's identical to CodeHashEQ.
func CodeHash(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEQ(FieldCodeHash, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEQ(FieldClientID, v))
}

// RedirectURI applies equality check predicate on the "redirect_uri" field. It's identical to RedirectURIEQ.
func RedirectURI(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEQ(FieldRedirectURI, v))
}

// CodeChallenge applies equality check predicate on the "code_challenge" field. It's identical to CodeChallengeEQ.
func CodeChallenge(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEQ(FieldCodeChallenge, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldLTE(FieldUpdatedAt, v))
}

// CodeHashEQ applies the EQ predicate on the "code_hash" field.
func CodeHashEQ(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEQ(FieldCodeHash, v))
}

// CodeHashNEQ applies the NEQ predicate on the "code_hash" field.
func CodeHashNEQ(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldNEQ(FieldCodeHash, v))
}

// CodeHashIn applies the In predicate on the "code_hash" field.
func CodeHashIn(vs ...string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldIn(FieldCodeHash, vs...))
}

// CodeHashNotIn applies the NotIn predicate on the "code_hash" field.
func CodeHashNotIn(vs ...string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldNotIn(FieldCodeHash, vs...))
}

// CodeHashGT applies the GT predicate on the "code_hash" field.
func CodeHashGT(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldGT(FieldCodeHash, v))
}

// CodeHashGTE applies the GTE predicate on the "code_hash" field.
func CodeHashGTE(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldGTE(FieldCodeHash, v))
}

// CodeHashLT applies the LT predicate on the "code_hash" field.
func CodeHashLT(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldLT(FieldCodeHash, v))
}

// CodeHashLTE applies the LTE predicate on the "code_hash" field.
func CodeHashLTE(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldLTE(FieldCodeHash, v))
}

// CodeHashContains applies the Contains predicate on the "code_hash" field.
func CodeHashContains(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldContains(FieldCodeHash, v))
}

// CodeHashHasPrefix applies the HasPrefix predicate on the "code_hash" field.
func CodeHashHasPrefix(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldHasPrefix(FieldCodeHash, v))
}

// CodeHashHasSuffix applies the HasSuffix predicate on the "code_hash" field.
func CodeHashHasSuffix(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldHasSuffix(FieldCodeHash, v))
}

// CodeHashEqualFold applies the EqualFold predicate on the "code_hash" field.
func CodeHashEqualFold(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEqualFold(FieldCodeHash, v))
}

// CodeHashContainsFold applies the ContainsFold predicate on the "code_hash" field.
func CodeHashContainsFold(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldContainsFold(FieldCodeHash, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldContainsFold(FieldClientID, v))
}

// RedirectURIEQ applies the EQ predicate on the "redirect_uri" field.
func RedirectURIEQ(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEQ(FieldRedirectURI, v))
}

// RedirectURINEQ applies the NEQ predicate on the "redirect_uri" field.
func RedirectURINEQ(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldNEQ(FieldRedirectURI, v))
}

// RedirectURIIn applies the In predicate on the "redirect_uri" field.
func RedirectURIIn(vs ...string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldIn(FieldRedirectURI, vs...))
}

// RedirectURINotIn applies the NotIn predicate on the "redirect_uri" field.
func RedirectURINotIn(vs ...string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldNotIn(FieldRedirectURI, vs...))
}

// RedirectURIGT applies the GT predicate on the "redirect_uri" field.
func RedirectURIGT(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldGT(FieldRedirectURI, v))
}

// RedirectURIGTE applies the GTE predicate on the "redirect_uri" field.
func RedirectURIGTE(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldGTE(FieldRedirectURI, v))
}

// RedirectURILT applies the LT predicate on the "redirect_uri" field.
func RedirectURILT(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldLT(FieldRedirectURI, v))
}

// RedirectURILTE applies the LTE predicate on the "redirect_uri" field.
func RedirectURILTE(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldLTE(FieldRedirectURI, v))
}

// RedirectURIContains applies the Contains predicate on the "redirect_uri" field.
func RedirectURIContains(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldContains(FieldRedirectURI, v))
}

// RedirectURIHasPrefix applies the HasPrefix predicate on the "redirect_uri" field.
func RedirectURIHasPrefix(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldHasPrefix(FieldRedirectURI, v))
}

// RedirectURIHasSuffix applies the HasSuffix predicate on the "redirect_uri" field.
func RedirectURIHasSuffix(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldHasSuffix(FieldRedirectURI, v))
}

// RedirectURIEqualFold applies the EqualFold predicate on the "redirect_uri" field.
func RedirectURIEqualFold(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEqualFold(FieldRedirectURI, v))
}

// RedirectURIContainsFold applies the ContainsFold predicate on the "redirect_uri" field.
func RedirectURIContainsFold(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldContainsFold(FieldRedirectURI, v))
}

// CodeChallengeEQ applies the EQ predicate on the "code_challenge" field.
func CodeChallengeEQ(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEQ(FieldCodeChallenge, v))
}

// CodeChallengeNEQ applies the NEQ predicate on the "code_challenge" field.
func CodeChallengeNEQ(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldNEQ(FieldCodeChallenge, v))
}

// CodeChallengeIn applies the In predicate on the "code_challenge" field.
func CodeChallengeIn(vs ...string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldIn(FieldCodeChallenge, vs...))
}

// CodeChallengeNotIn applies the NotIn predicate on the "code_challenge" field.
func CodeChallengeNotIn(vs ...string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldNotIn(FieldCodeChallenge, vs...))
}

// CodeChallengeGT applies the GT predicate on the "code_challenge" field.
func CodeChallengeGT(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldGT(FieldCodeChallenge, v))
}

// CodeChallengeGTE applies the GTE predicate on the "code_challenge" field.
func CodeChallengeGTE(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldGTE(FieldCodeChallenge, v))
}

// CodeChallengeLT applies the LT predicate on the "code_challenge" field.
func CodeChallengeLT(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldLT(FieldCodeChallenge, v))
}

// CodeChallengeLTE applies the LTE predicate on the "code_challenge" field.
func CodeChallengeLTE(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldLTE(FieldCodeChallenge, v))
}

// CodeChallengeContains applies the Contains predicate on the "code_challenge" field.
func CodeChallengeContains(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldContains(FieldCodeChallenge, v))
}

// CodeChallengeHasPrefix applies the HasPrefix predicate on the "code_challenge" field.
func CodeChallengeHasPrefix(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldHasPrefix(FieldCodeChallenge, v))
}

// CodeChallengeHasSuffix applies the HasSuffix predicate on the "code_challenge" field.
func CodeChallengeHasSuffix(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldHasSuffix(FieldCodeChallenge, v))
}

// CodeChallengeEqualFold applies the EqualFold predicate on the "code_challenge" field.
func CodeChallengeEqualFold(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEqualFold(FieldCodeChallenge, v))
}

// CodeChallengeContainsFold applies the ContainsFold predicate on the "code_challenge" field.
func CodeChallengeContainsFold(v string) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldContainsFold(FieldCodeChallenge, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.OAuthCode {
	return predicate.OAuthCode(sql.FieldLTE(FieldExpiresAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.OAuthCode {
	return predicate.OAuthCode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.OAuthCode {
	return predicate.OAuthCode(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthCode) predicate.OAuthCode {
	return predicate.OAuthCode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthCode) predicate.OAuthCode {
	return predicate.OAuthCode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthCode) predicate.OAuthCode {
	return predicate.OAuthCode(sql.NotPredicates(p))
}
