-- create "oauth_clients" table
CREATE TABLE "oauth_clients" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "client_id" character varying NOT NULL, "name" character varying NOT NULL DEFAULT '', "redirect_uris" jsonb NOT NULL, PRIMARY KEY ("id"));
-- create index "oauth_clients_client_id_key" to table: "oauth_clients"
CREATE UNIQUE INDEX "oauth_clients_client_id_key" ON "oauth_clients" ("client_id");
-- create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "email" text NOT NULL, "name" text NOT NULL, "password" text NOT NULL, "role" character varying NOT NULL, PRIMARY KEY ("id"));
-- create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
-- create "api_keys" table
CREATE TABLE "api_keys" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "name" character varying NOT NULL, "key_hash" character varying NOT NULL, "api_key_user" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "api_keys_users_user" FOREIGN KEY ("api_key_user") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "api_keys_key_hash_key" to table: "api_keys"
CREATE UNIQUE INDEX "api_keys_key_hash_key" ON "api_keys" ("key_hash");
-- create "photos" table
CREATE TABLE "photos" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "description" text NULL, "name" text NOT NULL, "url" text NULL, PRIMARY KEY ("id"));
-- create "authors" table
CREATE TABLE "authors" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "bio" text NULL, "name" text NOT NULL, "author_image" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "authors_photos_image" FOREIGN KEY ("author_image") REFERENCES "photos" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- create "sections" table
CREATE TABLE "sections" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "description" text NULL, "name" text NOT NULL, "slug" text NOT NULL, PRIMARY KEY ("id"));
-- create index "sections_slug_key" to table: "sections"
CREATE UNIQUE INDEX "sections_slug_key" ON "sections" ("slug");
-- create "categories" table
CREATE TABLE "categories" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "description" text NULL, "name" text NOT NULL, "slug" text NOT NULL, "category_section" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "categories_sections_section" FOREIGN KEY ("category_section") REFERENCES "sections" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- create index "categories_slug_key" to table: "categories"
CREATE UNIQUE INDEX "categories_slug_key" ON "categories" ("slug");
-- create "oauth_codes" table
CREATE TABLE "oauth_codes" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "code_hash" character varying NOT NULL, "client_id" character varying NOT NULL, "redirect_uri" character varying NOT NULL, "code_challenge" character varying NOT NULL, "expires_at" timestamptz NOT NULL, "oauth_code_user" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "oauth_codes_users_user" FOREIGN KEY ("oauth_code_user") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "oauth_codes_code_hash_key" to table: "oauth_codes"
CREATE UNIQUE INDEX "oauth_codes_code_hash_key" ON "oauth_codes" ("code_hash");
-- create "oauth_refreshes" table
CREATE TABLE "oauth_refreshes" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "token_hash" character varying NOT NULL, "client_id" character varying NOT NULL, "expires_at" timestamptz NOT NULL, "oauth_refresh_user" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "oauth_refreshes_users_user" FOREIGN KEY ("oauth_refresh_user") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "oauth_refreshes_token_hash_key" to table: "oauth_refreshes"
CREATE UNIQUE INDEX "oauth_refreshes_token_hash_key" ON "oauth_refreshes" ("token_hash");
-- create "posts" table
CREATE TABLE "posts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "brief" jsonb NULL, "content" jsonb NULL, "other_byline" text NULL, "publish_time" timestamptz NULL, "state" character varying NOT NULL DEFAULT 'draft', "subtitle" text NULL, "title" text NOT NULL, "post_hero_image" bigint NULL, "post_section" bigint NULL, "post_created_by" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "posts_photos_hero_image" FOREIGN KEY ("post_hero_image") REFERENCES "photos" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "posts_sections_section" FOREIGN KEY ("post_section") REFERENCES "sections" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "posts_users_created_by" FOREIGN KEY ("post_created_by") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- create "post_categories" table
CREATE TABLE "post_categories" ("post_id" bigint NOT NULL, "category_id" bigint NOT NULL, PRIMARY KEY ("post_id", "category_id"), CONSTRAINT "post_categories_category_id" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "post_categories_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- create "post_related_posts" table
CREATE TABLE "post_related_posts" ("post_id" bigint NOT NULL, "related_post_id" bigint NOT NULL, PRIMARY KEY ("post_id", "related_post_id"), CONSTRAINT "post_related_posts_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "post_related_posts_related_post_id" FOREIGN KEY ("related_post_id") REFERENCES "posts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- create "tags" table
CREATE TABLE "tags" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "brief" text NULL, "is_featured" boolean NOT NULL DEFAULT false, "name" text NOT NULL, "sort_order" bigint NULL, PRIMARY KEY ("id"));
-- create index "tags_name_key" to table: "tags"
CREATE UNIQUE INDEX "tags_name_key" ON "tags" ("name");
-- create "post_tags" table
CREATE TABLE "post_tags" ("post_id" bigint NOT NULL, "tag_id" bigint NOT NULL, PRIMARY KEY ("post_id", "tag_id"), CONSTRAINT "post_tags_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "post_tags_tag_id" FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- create "post_writers" table
CREATE TABLE "post_writers" ("post_id" bigint NOT NULL, "author_id" bigint NOT NULL, PRIMARY KEY ("post_id", "author_id"), CONSTRAINT "post_writers_author_id" FOREIGN KEY ("author_id") REFERENCES "authors" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "post_writers_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
