package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/hcchien/nl/ent"
)

// CreateAuthor is the resolver for the createAuthor field.
func (r *mutationResolver) CreateAuthor(ctx context.Context, input ent.CreateAuthorInput) (*ent.Author, error) {
	return r.Client.Author.Create().SetInput(input).Save(ctx)
}

// UpdateAuthor is the resolver for the updateAuthor field.
func (r *mutationResolver) UpdateAuthor(ctx context.Context, id int, input ent.UpdateAuthorInput) (*ent.Author, error) {
	return r.Client.Author.UpdateOneID(id).SetInput(input).Save(ctx)
}

// DeleteAuthor is the resolver for the deleteAuthor field.
func (r *mutationResolver) DeleteAuthor(ctx context.Context, id int) (int, error) {
	if err := r.Client.Author.DeleteOneID(id).Exec(ctx); err != nil {
		return 0, err
	}
	return id, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input ent.CreateCategoryInput) (*ent.Category, error) {
	return r.Client.Category.Create().SetInput(input).Save(ctx)
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id int, input ent.UpdateCategoryInput) (*ent.Category, error) {
	return r.Client.Category.UpdateOneID(id).SetInput(input).Save(ctx)
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id int) (int, error) {
	if err := r.Client.Category.DeleteOneID(id).Exec(ctx); err != nil {
		return 0, err
	}
	return id, nil
}

// CreatePhoto is the resolver for the createPhoto field.
func (r *mutationResolver) CreatePhoto(ctx context.Context, input ent.CreatePhotoInput) (*ent.Photo, error) {
	return r.Client.Photo.Create().SetInput(input).Save(ctx)
}

// UpdatePhoto is the resolver for the updatePhoto field.
func (r *mutationResolver) UpdatePhoto(ctx context.Context, id int, input ent.UpdatePhotoInput) (*ent.Photo, error) {
	return r.Client.Photo.UpdateOneID(id).SetInput(input).Save(ctx)
}

// DeletePhoto is the resolver for the deletePhoto field.
func (r *mutationResolver) DeletePhoto(ctx context.Context, id int) (int, error) {
	if err := r.Client.Photo.DeleteOneID(id).Exec(ctx); err != nil {
		return 0, err
	}
	return id, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input ent.CreatePostInput) (*ent.Post, error) {
	return r.Client.Post.Create().SetInput(input).Save(ctx)
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, id int, input ent.UpdatePostInput) (*ent.Post, error) {
	return r.Client.Post.UpdateOneID(id).SetInput(input).Save(ctx)
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id int) (int, error) {
	if err := r.Client.Post.DeleteOneID(id).Exec(ctx); err != nil {
		return 0, err
	}
	return id, nil
}

// CreateSection is the resolver for the createSection field.
func (r *mutationResolver) CreateSection(ctx context.Context, input ent.CreateSectionInput) (*ent.Section, error) {
	return r.Client.Section.Create().SetInput(input).Save(ctx)
}

// UpdateSection is the resolver for the updateSection field.
func (r *mutationResolver) UpdateSection(ctx context.Context, id int, input ent.UpdateSectionInput) (*ent.Section, error) {
	return r.Client.Section.UpdateOneID(id).SetInput(input).Save(ctx)
}

// DeleteSection is the resolver for the deleteSection field.
func (r *mutationResolver) DeleteSection(ctx context.Context, id int) (int, error) {
	if err := r.Client.Section.DeleteOneID(id).Exec(ctx); err != nil {
		return 0, err
	}
	return id, nil
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, input ent.CreateTagInput) (*ent.Tag, error) {
	return r.Client.Tag.Create().SetInput(input).Save(ctx)
}

// UpdateTag is the resolver for the updateTag field.
func (r *mutationResolver) UpdateTag(ctx context.Context, id int, input ent.UpdateTagInput) (*ent.Tag, error) {
	return r.Client.Tag.UpdateOneID(id).SetInput(input).Save(ctx)
}

// DeleteTag is the resolver for the deleteTag field.
func (r *mutationResolver) DeleteTag(ctx context.Context, id int) (int, error) {
	if err := r.Client.Tag.DeleteOneID(id).Exec(ctx); err != nil {
		return 0, err
	}
	return id, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input ent.CreateUserInput) (*ent.User, error) {
	return r.Client.User.Create().SetInput(input).Save(ctx)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id int, input ent.UpdateUserInput) (*ent.User, error) {
	return r.Client.User.UpdateOneID(id).SetInput(input).Save(ctx)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id int) (int, error) {
	if err := r.Client.User.DeleteOneID(id).Exec(ctx); err != nil {
		return 0, err
	}
	return id, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
