package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"

	"github.com/hcchien/nl/auth"
	"github.com/hcchien/nl/ent"
	"github.com/hcchien/nl/ent/user"
	"github.com/hcchien/nl/graph/model"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	// 登入本身不受權限系統管轄，走 system context 查詢
	sys := auth.WithSystem(ctx)
	u, err := r.Client.User.Query().Where(user.EmailEQ(email)).Only(sys)
	if err != nil || !auth.VerifyPassword(u.Password, password) {
		return nil, gqlerror.Errorf("invalid email or password")
	}
	return &model.AuthPayload{
		Token: auth.SignToken(r.TokenSecret, u.ID, sessionTTL),
		User:  u,
	}, nil
}

// CreateAPIKey is the resolver for the createApiKey field.
func (r *mutationResolver) CreateAPIKey(ctx context.Context, name string) (*model.APIKeyPayload, error) {
	v := auth.ViewerFrom(ctx)
	if v == nil {
		return nil, gqlerror.Errorf("authentication required")
	}
	plain, hash := auth.NewAPIKey()
	if _, err := r.Client.ApiKey.Create().
		SetName(name).
		SetKeyHash(hash).
		SetUserID(v.ID).
		Save(auth.WithSystem(ctx)); err != nil {
		return nil, err
	}
	return &model.APIKeyPayload{Key: plain, Name: name}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*ent.User, error) {
	v := auth.ViewerFrom(ctx)
	if v == nil {
		return nil, nil
	}
	return r.Client.User.Get(auth.WithSystem(ctx), v.ID)
}
