// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (_m *Author) Image(ctx context.Context) (*Photo, error) {
	result, err := _m.Edges.ImageOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryImage().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Author) Posts(ctx context.Context) (result []*Post, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedPosts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.PostsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryPosts().All(ctx)
	}
	return result, err
}

func (_m *Category) Section(ctx context.Context) (*Section, error) {
	result, err := _m.Edges.SectionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QuerySection().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Category) Posts(ctx context.Context) (result []*Post, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedPosts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.PostsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryPosts().All(ctx)
	}
	return result, err
}

func (_m *Post) Categories(ctx context.Context) (result []*Category, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedCategories(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.CategoriesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryCategories().All(ctx)
	}
	return result, err
}

func (_m *Post) HeroImage(ctx context.Context) (*Photo, error) {
	result, err := _m.Edges.HeroImageOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryHeroImage().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Post) RelatedPosts(ctx context.Context) (result []*Post, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedRelatedPosts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.RelatedPostsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryRelatedPosts().All(ctx)
	}
	return result, err
}

func (_m *Post) Section(ctx context.Context) (*Section, error) {
	result, err := _m.Edges.SectionOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QuerySection().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Post) Tags(ctx context.Context) (result []*Tag, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedTags(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.TagsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryTags().All(ctx)
	}
	return result, err
}

func (_m *Post) Writers(ctx context.Context) (result []*Author, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedWriters(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.WritersOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryWriters().All(ctx)
	}
	return result, err
}

func (_m *Post) CreatedBy(ctx context.Context) (*User, error) {
	result, err := _m.Edges.CreatedByOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryCreatedBy().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Section) Categories(ctx context.Context) (result []*Category, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedCategories(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.CategoriesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryCategories().All(ctx)
	}
	return result, err
}

func (_m *Section) Posts(ctx context.Context) (result []*Post, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedPosts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.PostsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryPosts().All(ctx)
	}
	return result, err
}

func (_m *Tag) Posts(ctx context.Context) (result []*Post, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedPosts(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.PostsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryPosts().All(ctx)
	}
	return result, err
}
