// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hcchien/nl/ent/oauthrefresh"
	"github.com/hcchien/nl/ent/predicate"
	"github.com/hcchien/nl/ent/user"
)

// OAuthRefreshUpdate is the builder for updating OAuthRefresh entities.
type OAuthRefreshUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthRefreshMutation
}

// Where appends a list predicates to the OAuthRefreshUpdate builder.
func (_u *OAuthRefreshUpdate) Where(ps ...predicate.OAuthRefresh) *OAuthRefreshUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthRefreshUpdate) SetUpdatedAt(v time.Time) *OAuthRefreshUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *OAuthRefreshUpdate) SetTokenHash(v string) *OAuthRefreshUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *OAuthRefreshUpdate) SetNillableTokenHash(v *string) *OAuthRefreshUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthRefreshUpdate) SetClientID(v string) *OAuthRefreshUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthRefreshUpdate) SetNillableClientID(v *string) *OAuthRefreshUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthRefreshUpdate) SetExpiresAt(v time.Time) *OAuthRefreshUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthRefreshUpdate) SetNillableExpiresAt(v *time.Time) *OAuthRefreshUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *OAuthRefreshUpdate) SetUserID(id int) *OAuthRefreshUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OAuthRefreshUpdate) SetUser(v *User) *OAuthRefreshUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the OAuthRefreshMutation object of the builder.
func (_u *OAuthRefreshUpdate) Mutation() *OAuthRefreshMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OAuthRefreshUpdate) ClearUser() *OAuthRefreshUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthRefreshUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthRefreshUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthRefreshUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthRefreshUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthRefreshUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthrefresh.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthRefreshUpdate) check() error {
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := oauthrefresh.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthRefresh.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthrefresh.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthRefresh.client_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthRefresh.user"`)
	}
	return nil
}

func (_u *OAuthRefreshUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthrefresh.Table, oauthrefresh.Columns, sqlgraph.NewFieldSpec(oauthrefresh.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthrefresh.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(oauthrefresh.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthrefresh.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthrefresh.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   oauthrefresh.UserTable,
			Columns: []string{oauthrefresh.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   oauthrefresh.UserTable,
			Columns: []string{oauthrefresh.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthrefresh.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthRefreshUpdateOne is the builder for updating a single OAuthRefresh entity.
type OAuthRefreshUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthRefreshMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthRefreshUpdateOne) SetUpdatedAt(v time.Time) *OAuthRefreshUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *OAuthRefreshUpdateOne) SetTokenHash(v string) *OAuthRefreshUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *OAuthRefreshUpdateOne) SetNillableTokenHash(v *string) *OAuthRefreshUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthRefreshUpdateOne) SetClientID(v string) *OAuthRefreshUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthRefreshUpdateOne) SetNillableClientID(v *string) *OAuthRefreshUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthRefreshUpdateOne) SetExpiresAt(v time.Time) *OAuthRefreshUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthRefreshUpdateOne) SetNillableExpiresAt(v *time.Time) *OAuthRefreshUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *OAuthRefreshUpdateOne) SetUserID(id int) *OAuthRefreshUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OAuthRefreshUpdateOne) SetUser(v *User) *OAuthRefreshUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the OAuthRefreshMutation object of the builder.
func (_u *OAuthRefreshUpdateOne) Mutation() *OAuthRefreshMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OAuthRefreshUpdateOne) ClearUser() *OAuthRefreshUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the OAuthRefreshUpdate builder.
func (_u *OAuthRefreshUpdateOne) Where(ps ...predicate.OAuthRefresh) *OAuthRefreshUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthRefreshUpdateOne) Select(field string, fields ...string) *OAuthRefreshUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthRefresh entity.
func (_u *OAuthRefreshUpdateOne) Save(ctx context.Context) (*OAuthRefresh, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthRefreshUpdateOne) SaveX(ctx context.Context) *OAuthRefresh {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthRefreshUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthRefreshUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthRefreshUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthrefresh.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthRefreshUpdateOne) check() error {
	if v, ok := _u.mutation.TokenHash(); ok {
		if err := oauthrefresh.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "OAuthRefresh.token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthrefresh.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthRefresh.client_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthRefresh.user"`)
	}
	return nil
}

func (_u *OAuthRefreshUpdateOne) sqlSave(ctx context.Context) (_node *OAuthRefresh, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthrefresh.Table, oauthrefresh.Columns, sqlgraph.NewFieldSpec(oauthrefresh.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthRefresh.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthrefresh.FieldID)
		for _, f := range fields {
			if !oauthrefresh.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthrefresh.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthrefresh.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(oauthrefresh.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthrefresh.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthrefresh.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   oauthrefresh.UserTable,
			Columns: []string{oauthrefresh.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   oauthrefresh.UserTable,
			Columns: []string{oauthrefresh.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OAuthRefresh{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthrefresh.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
