// Code generated by nl gen. DO NOT EDIT.

package access

import (
	"context"

	"entgo.io/ent/dialect/sql"

	gen "github.com/hcchien/nl/ent"
	"github.com/hcchien/nl/ent/post"
	"github.com/hcchien/nl/ent/user"
)

// ownerPredicate 回傳 list 的「createdBy = viewer」predicate。
func ownerPredicate(list string, uid int) (func(*sql.Selector), bool) {
	switch list {
	case "Post":
		return post.HasCreatedByWith(user.IDEQ(uid)), true
	}
	return nil, false
}

// ownedExists 檢查單筆 mutation 的目標是否屬於 viewer；bulk mutation 回傳 single=false。
func ownedExists(ctx context.Context, m gen.Mutation, uid int) (owned, single bool, err error) {
	switch mm := m.(type) {
	case *gen.PostMutation:
		id, ok := mm.ID()
		if !ok {
			return false, false, nil
		}
		owned, err = mm.Client().Post.Query().Where(post.ID(id), post.HasCreatedByWith(user.IDEQ(uid))).Exist(ctx)
		return owned, true, err
	}
	return false, false, nil
}

// setCreator 在 create 時自動掛上 viewer（宣告了 nl.TrackCreator 的 lists）。
func setCreator(m gen.Mutation, uid int) {
	switch mm := m.(type) {
	case *gen.PostMutation:
		if _, ok := mm.CreatedByID(); !ok {
			mm.SetCreatedByID(uid)
		}
	}
}
