// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ApiKey is the predicate function for apikey builders.
type ApiKey func(*sql.Selector)

// Author is the predicate function for author builders.
type Author func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// OAuthClient is the predicate function for oauthclient builders.
type OAuthClient func(*sql.Selector)

// OAuthCode is the predicate function for oauthcode builders.
type OAuthCode func(*sql.Selector)

// Photo is the predicate function for photo builders.
type Photo func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Section is the predicate function for section builders.
type Section func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
